schoolbus {
  db {
    profile = "slick.jdbc.PostgresProfile$"
    db {
      url = "jdbc:postgresql://localhost:5432/schoolbus"
      url = ${?SCHOOLBUS_DB_URL}
      user = "schoolbus"
      user = ${?SCHOOLBUS_DB_USER}
      password = "schoolbus"
      password = ${?SCHOOLBUS_DB_PASSWORD}
      driver = "org.postgresql.Driver"
      numThreads = 10
      connectionPool = "HikariCP"
    }
  }
}
